version: "3.7"
services:

  app:
    image: henriquerluz/php-fpm:1.0.0
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker-compose/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - invest-network
    depends_on:
      - "db_invest"

  db_invest:
    build:
      context: ./docker-compose/postgres
      dockerfile: Dockerfile
    image: invest_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: invest
      POSTGRES_PASSWORD: invest
      POSTGRES_USER: postgres
    volumes:
      - ./docker-compose/postgres:/docker-entrypoint-initdb.d
      - ./docker-compose/postgres/db-data:/var/lib/postgresql/data
    networks:
      - invest-network

  apache:
    build:
      context: ./docker-compose/apache
      dockerfile: Dockerfile
    image: web-invest-apache
    depends_on:
      - app
    networks:
      - invest-network
    ports:
      - "80:80"
    volumes:
      - ./:/var/www

  invest_bot:
    image: selenium/standalone-chrome:95.0
    ports:
      - "4444:4444"
    shm_size: 2gb
    networks:
      - invest-network

networks:
  invest-network:
    driver: bridge
