version: "3.7"
services:
  app:
    build:
      args:
        user: invest
        uid: 1000
      context: ./docker-compose/php
      dockerfile: Dockerfile
    image: invest_app
    working_dir: /var/www/
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
      - ./docker-compose/php/php:/usr/local/etc/php
    networks:
      - invest-network
    depends_on:
      - "db_invest"

  db_invest:
    build:
      context: ./docker-compose/postgres
      dockerfile: Dockerfile
    image: invest_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: invest
      POSTGRES_PASSWORD: invest
      POSTGRES_USER: postgres
    volumes:
      - ./docker-compose/postgres:/docker-entrypoint-initdb.d
      - ./docker-compose/postgres/db-data:/var/lib/postgresql/data
    networks:
      - invest-network

  #nginx:
  #  image: nginx:alpine
  #  ports:
  #    - "80:80"
  #  volumes:
  #    - ./:/var/www
  #    - ./docker-compose/nginx:/etc/nginx/conf.d
  #  networks:
  #    - invest-network
  #  depends_on:
  #    - "app"

  apache:
    build:
      context: ./docker-compose/apache
      dockerfile: Dockerfile
    depends_on:
      - app
    networks:
      - invest-network
    ports:
      - "80:80"
    volumes:
      - ./:/var/www

  invest_bot:
    image: selenium/standalone-chrome:95.0
    ports:
      - "4444:4444"
    shm_size: 2gb
    #network_mode: "host"
    networks:
      - invest-network

networks:
  invest-network:
    driver: bridge
